### ISSUE TITLE
Has this been dropped?

### ISSUE THREAD

**Issue by tonypartridge** [netvlies/basecamp-php#42]
Doesn't look like it works. Composer cannot find the package at any version?

**Comment by nickedwards** [comment]
https://packagist.org/packages/netvlies/basecamp-php still exists, what is the error you're getting?

**Comment by tonypartridge** [comment]
It couldn't find the package. I downloaded the Json file manually and just ran the install in the end.

Although Basecamp3 sucks now and we have decided to move to ActiveCollab. So this can be closed :-)
